CREATE TABLE IF NOT EXISTS rate_limits (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  rate_key VARCHAR(191) NOT NULL,
  hits INT UNSIGNED NOT NULL DEFAULT 1,
  reset_at DATETIME NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_rate_key (rate_key),
  INDEX idx_reset_at (reset_at)
) ENGINE=InnoDB;
